#!/usr/bin/env python3
"""bin2h.py — convert a binary file to a C header byte array.

Usage: bin2h.py <input.bin> <output.h> <symbol>

Emits:
    const unsigned char <symbol>[] = { ... };
    const unsigned int  <symbol>_size = <N>;

Pads the data up to a 16-byte multiple (GBA multiboot requirement).
"""
import sys, os

def main():
    if len(sys.argv) != 4:
        sys.exit("usage: bin2h.py <input.bin> <output.h> <symbol>")
    inp, out, sym = sys.argv[1], sys.argv[2], sys.argv[3]

    with open(inp, "rb") as f:
        data = bytearray(f.read())

    # pad to 16-byte multiple
    while len(data) % 16:
        data.append(0)

    lines = []
    lines.append(f"// Auto-generated by bin2h.py from {os.path.basename(inp)} - do not edit by hand.")
    lines.append("#pragma once")
    lines.append("")
    lines.append(f"const unsigned char {sym}[] = {{")
    for i in range(0, len(data), 12):
        chunk = data[i:i+12]
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in chunk) + ",")
    lines.append("};")
    lines.append(f"const unsigned int {sym}_size = {len(data)};")
    lines.append("")

    with open(out, "w") as f:
        f.write("\n".join(lines))

    print(f"{inp} -> {out}  ({len(data)} bytes, symbol '{sym}')")

if __name__ == "__main__":
    main()
