#!/usr/bin/env python3
"""gen_notes.py — emit payload/notes.h: the GBA PSG period register for every MIDI note.

The GBA square channels run at  f = 131072 / (2048 - n)  (GBATEK, SOUND1CNT_X bits 0-10), so
the register value is  n = 2048 - 131072/f.  ARM7TDMI has NO divide instruction and we link
-nostdlib (no libgcc, so no __aeabi_uidiv either), which makes a runtime divide a link error
rather than merely slow. A baked table sidesteps that completely.

Sub-semitone pitch is linear interpolation BETWEEN table entries, and that is exact rather
than approximate: the register is an affine function of 1/f, so interpolating the register is
interpolating the period.

The wave channel runs at half the rate for the same register value (f = 65536 / (2048 - n)),
i.e. exactly one octave down, so channel 3 just indexes this same table 12 entries higher.

Regenerate with:  python payload/gen_notes.py
"""

OUT = "notes.h"

# Lowest playable note. Below ~64 Hz the register would need to be negative:
#   f = 131072/2048 = 64 Hz is the floor, and MIDI 36 (C2) is 65.406 Hz — just above it.
MIN_NOTE = 36


def period_for(note):
    freq = 440.0 * (2.0 ** ((note - 69) / 12.0))
    reg = 2048.0 - (131072.0 / freq)
    if reg < 0.0:
        return 0
    if reg > 2047.0:
        return 2047
    return int(round(reg))


def main():
    vals = [period_for(n) for n in range(128)]

    with open(OUT, "w", newline="\n") as f:
        f.write("// notes.h - GENERATED by gen_notes.py. Do not edit by hand.\n")
        f.write("//\n")
        f.write("// GBA PSG square-channel period register per MIDI note: n = 2048 - 131072/f.\n")
        f.write("// Entries below MIDI %d are unreachable (the register would go negative) and\n" % MIN_NOTE)
        f.write("// are set to 0; clamp to NOTE_MIN before indexing.\n")
        f.write("//\n")
        f.write("// The WAVE channel is one octave lower for the same register value, so channel 3\n")
        f.write("// uses NOTE_PERIOD[note + 12].\n")
        f.write("#pragma once\n\n")
        f.write("#include <stdint.h>\n\n")
        f.write("#define NOTE_MIN %d\n" % MIN_NOTE)
        f.write("#define NOTE_MAX 127\n\n")
        f.write("static const uint16_t NOTE_PERIOD[128] = {\n")
        for i in range(0, 128, 8):
            row = ", ".join("%4d" % v for v in vals[i:i + 8])
            f.write("    %s,%s// %d\n" % (row, " " * 3, i))
        f.write("};\n")

    print("wrote %s (MIDI %d..127 playable)" % (OUT, MIN_NOTE))


if __name__ == "__main__":
    main()
