// notes.h - GENERATED by gen_notes.py. Do not edit by hand.
//
// GBA PSG square-channel period register per MIDI note: n = 2048 - 131072/f.
// Entries below MIDI 36 are unreachable (the register would go negative) and
// are set to 0; clamp to NOTE_MIN before indexing.
//
// The WAVE channel is one octave lower for the same register value, so channel 3
// uses NOTE_PERIOD[note + 12].
#pragma once

#include <stdint.h>

#define NOTE_MIN 36
#define NOTE_MAX 127

static const uint16_t NOTE_PERIOD[128] = {
       0,    0,    0,    0,    0,    0,    0,    0,   // 0
       0,    0,    0,    0,    0,    0,    0,    0,   // 8
       0,    0,    0,    0,    0,    0,    0,    0,   // 16
       0,    0,    0,    0,    0,    0,    0,    0,   // 24
       0,    0,    0,    0,   44,  157,  263,  363,   // 32
     457,  547,  631,  711,  786,  856,  923,  986,   // 40
    1046, 1102, 1155, 1205, 1253, 1297, 1339, 1379,   // 48
    1417, 1452, 1486, 1517, 1547, 1575, 1602, 1627,   // 56
    1650, 1673, 1694, 1714, 1732, 1750, 1767, 1783,   // 64
    1798, 1812, 1825, 1837, 1849, 1860, 1871, 1881,   // 72
    1890, 1899, 1907, 1915, 1923, 1930, 1936, 1943,   // 80
    1949, 1954, 1959, 1964, 1969, 1974, 1978, 1982,   // 88
    1985, 1989, 1992, 1995, 1998, 2001, 2004, 2006,   // 96
    2009, 2011, 2013, 2015, 2017, 2018, 2020, 2022,   // 104
    2023, 2025, 2026, 2027, 2028, 2029, 2030, 2031,   // 112
    2032, 2033, 2034, 2035, 2036, 2036, 2037, 2038,   // 120
};
